[project]
name = "agio-launcher"
version = "0.0.4"
requires-python = ">=3.11"
dependencies = []
license = "MIT"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"agio_launcher" = [
    "__agio__.yml",
]